asset/urls.py
from django.conf.urls import include, url
from asset import asset, asset_type
from .stock.urls import stock_patterns

app_name = "asset"

asset_type_patterns = ([
    url(r'^asset_type/', include([

        url(r'^create/$', asset_type.create, name="create"),
        url(r'^asset_category/$', asset_type.asset_category, name="asset_category"),

    ])),

], 'asset_type')


urlpatterns = [

    url(r'^asset/', include([
        url(r'^index/$', asset.index, name="list"),
        url(r'^dashboard/$', asset.dashboard, name="dashboard"),
        url(r'^create/$', asset.create, name="create"),
        url(r'^customer/asset/create/$', asset.customer_asset_create, name="customer_asset_create"),
        url(r'^customer/asset/(?P<pk>[^/]+)/edit/$', asset.customer_asset_edit, name="customer_asset_edit"),
        url(r'^(?P<pk>[^/]+)/edit/$', asset.edit, name="edit"),
        url(r'^(?P<pk>[^/]+)/detail/$', asset.detail, name="detail"),
        url(r'^(?P<pk>[^/]+)/delete/$', asset.delete, name="delete"),
        url(r'^stocks/', include(stock_patterns, namespace="stock")),
        url(r'^code/settings/$', asset.code_settings, name='code_settings'),
        url(r'^(?P<barcode>[^/]+)/transaction/$', asset.asset_transaction, name="asset_transaction"),

    ])),
    url(r'^asset/', include(asset_type_patterns)),
    url(r'^transaction/(?P<pk>[^/]+)/detail/$', asset.transaction_detail, name="transaction_detail"),
    url(r'^customer/transactions/(?P<selectedDate>[^/]+)/$', asset.customer_transaction, name="customer_transaction"),
    url(r'^customer/transactions/$', asset.customer_transaction, name="customer_transaction"),
    url(r'^customer/assets/(?P<date>[^/]+)/(?P<customer>[^/]+)/$', asset.customer_asset, name="customer_asset"),
    url(r'^asset/change/status/(?P<pk>[^/]+)/$', asset.changeStatus, name="changeStatus"),
    url(r'^employee/assets/$', asset.employee_assets, name="employee_assets"),
    url(r'^return/asset/(?P<pk>[^/]+)/$', asset.return_asset, name="return_asset"),


]

customer/urls.py
from django.conf.urls import include, url
from rest_framework import routers
from django.views.decorators.csrf import csrf_exempt
from customer import api, customer, contact, address,address_api

app_name = "customer"

# router = routers.DefaultRouter()
# router.register(r'customers', api.CustomerViewSet, base_name="customer")
# router.register(r'contacts', api.ContactViewSet, base_name="contact")
# m_router = routers.DefaultRouter()
# m_router.register(r'address', address_api.AddressCreateViewSet, base_name="contact_address")
# router.register(r'addresses', api.AddressViewSet, base_name="address")

# customer_list = api.CustomerViewSet.as_view({'get': 'list'})
# customer_create = api.CustomerViewSet.as_view({'get': 'create_form'})
# customer_retrieve = api.CustomerViewSet.as_view({'get': 'retrieve'})
# customer_edit = api.CustomerViewSet.as_view({'get': 'edit_form'})
# contact_retrieve = api.ContactViewSet.as_view({'get': 'retrieve'})
# contact_select_list = api.ContactViewSet.as_view({'get': 'select_list'})


urlpatterns = [
    # url(r'^$', views.index, name="list"),
    # url(r'^customers$', customer_list, name="customers"),
    # Customer urls
    url(r'^customers/$', customer.list, name="list"),
    url(r'^customers/create/$', customer.create, name="create"),
    url(r'^customers/(?P<pk>[^/]+)/transactions/$', customer.all_transactions, name="transactions"),
    url(r'^customers/(?P<pk>[^/]+)/$', customer.detail, name="detail"),
    url(r'^customers/(?P<pk>[^/]+)/edit/$', customer.edit, name="edit"),
    url(r'^customers/(?P<pk>[^/]+)/delete/$', customer.delete, name="delete"),

    # Contact Urls
    url(r'^contacts/(?P<pk>[^/]+)/$', contact.detail, name="contact-detail"),
    url(r'^customer/(?P<barcode>[^/]+)/new/create/$', customer.customer_new_create, name="customer_new_create"),


]


# GET api/enquiries/ => customer list
# GET api/enquiries/choices => customer choice fields
# POST api/enquiries/  => create customer
# PUT api/enquiries/{pk}  => update customer
# DELETE api/enquiries/{pk}  => delete customer

papercraneerp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from sitetree.sitetreeapp import compose_dynamic_tree, register_dynamic_trees
from erp_admin import views as erpAdminViews


# from employee import views as employeeViews
urlpatterns = [
    url(r'^$', erpAdminViews.dashboard),
    # url(r'^api-token-auth/', views.obtain_auth_token),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('employee.urls', namespace="employee")),
    url(r'^', include('customer.urls', namespace="customer")),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include('location.urls', namespace="location")),
    url(r'^company/', include('company.urls', namespace="company")),
    url(r'^', include('asset.urls', namespace="asset")),




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns = static(settings.MEDIA_URL, view=never_cache(serve_static),
#                          document_root=settings.MEDIA_ROOT) + urlpatterns
admin.site.site_header = 'Jawdrop Administration'




register_dynamic_trees(

    compose_dynamic_tree('erp_admin'),

    # or gather all the trees from `books` and attach them to `main` tree root,
    compose_dynamic_tree('employee'),
    compose_dynamic_tree('customer'),
    compose_dynamic_tree('asset'),





)

customer/models.py
from django.conf import settings
from django.db import models
from erp_core.models import BaseModel



class Customer(BaseModel):
    code = models.CharField(max_length=100, unique=True, null=True)
    name = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    refered_by = models.ForeignKey('employee.Employee', on_delete=models.CASCADE, null=True, blank=True)
    address = models.TextField(null=True)
    phone = models.CharField(max_length=20,null=True)

    # category = models.ManyToManyField('customer.Category')

    def __str__(self):
        name = self.name
        if self.code:
            name += "(" + str(self.code) + ")"
        return name

customer/forms.py
from django import forms
from django.forms import ModelForm
from customer.models import Customer


class CustomerForm(ModelForm):

    class Meta:
        model = Customer
        widgets = {
            "name": forms.TextInput(attrs={'class': "form-control", 'required': "required"}),
            "phone": forms.NumberInput(attrs={'class': "form-control", 'required': "required"}),
            "address": forms.Textarea(attrs={'class': "form-control", 'required': "required"}),

        }
        fields = ['name','phone','address']

customer/templates/customer/detail.html
{% extends "erp_admin/base.html" %}
{% load static tz group_required %}
{% get_current_timezone as TIME_ZONE %}
{% block head %}
<style>
.co{
    color:#d9534f;
}

.list-group-item:last-child {
    margin-bottom: 0;
    border-bottom-right-radius: 32px;
    border-bottom-left-radius: 32px;
}

.list-group-item:first-child {
    border-top-left-radius: 32px;
    border-top-right-radius: 32px;
}
.profile {
    min-height: 473px;

}
.btn {
    border-radius: 8px!important;
    }

th{
    color:#337ab7!important;
}
td{
    color:#000000!important;
}

</style>
{% endblock head %}

{% block content %}

<div class="banner">
    <h2>
        <a href="/">Customer</a>
        <i class="fa fa-angle-right"></i>
        <span>{{customer}}</span>
        <a href="" class="pull-right"><i class="fa fa-times"></i></a>
    </h2>
</div>
<div class="block">
    <div class="row show-grid">
        <div class="col-sm-12 col-xs-12">
            <div class="pull-right">
                <a href="{% url 'customer:edit' customer.pk %}" class="btn btn-primary btn-xs">
                    <i class="fa fa-pencil-square-o fa-fw"></i> Edit
                </a>
                <form method="post" action="{% url 'customer:delete' customer.pk %}" onsubmit="remove(this, event)"
                      style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-xs">
                        <i class="fa fa-trash-o fa-fw"></i> Delete
                    </button>
                </form>
            </div>
        </div>
    </div>
    <div class="row show-grid">
        <div class="profile">
            <div class="profile-bottom" style="width: 100%;">
                <h3><i style="color:#337ab7;" class="fa fa-user"></i>{{customer}}</h3>
                <div class="profile-bottom-top">
                    <div class="col-xs-12 col-sm-12 col-md-8 profile-text">
                        <table class="col-xs-12">
                            <tr>
                                <td>Name :
                                    {{customer.name}}
                                </td>
                            </tr>
                            <tr>
                                <td>Phone :
                                    {{customer.phone}}
                                </td>
                            </tr>
                            <tr>
                                <td>Address :
                                    {{customer.address}}
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div class="clearfix">
                    </div>
                </div>
            </div>
            <div class="profile-bottom" style="width: 100%;">
                <h3><i style="color:#337ab7;" class="fa fa-stethoscope"></i>Transaction history</h3>
                <div class="profile-bottom-top">
                    <div class="col-xs-12 col-sm-12 col-md-12 profile-text">
                        <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Date and time</th>
                            <th>Incharge</th>
                            <th>More Details</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for transaction in transactions %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td scope="row">{{ transaction.0 | date }}</td>
                            <td scope="row">{{ transaction.1 }}</td>
                            <td><a href="{% url 'customer:transactions' customer.pk %}?date={{ transaction.0 | date:'Y-m-d' }}"><i class="fa fa-external-link"></i></a></td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="6">No Data</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    </div>
                    <div class="clearfix">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}
{% block jsscript %}
<script>

  $('form.delete').submit( function (e){
        e.preventDefault()
        e.stopPropagation()
        if(confirm('Do you want to Delete the entire student Details')){
            this.submit()
        }
    })
</script>

{% endblock jsscript %}

customer/templates/customer/detail_api.html
{% extends "erp_admin/base.html" %}
{% load static tz %}
{% get_current_timezone as TIME_ZONE %}
{% block head %}
<style>
</style>
{% endblock head %}

{% block content %}
<div id="app"> </div>
{% endblock content %}

{% block jsscript %}
<script >
    var customer = {{data | safe | escape}}
    console.log(customer)
</script>
<script src="{% static 'js/jquery.chained.min.js' %}"></script>
<script src="{% static 'js/bundles/vendor.bundle.js' %}"></script>
<script src="{% static 'js/bundles/customer_detail.js' %}"></script>
{% endblock jsscript %}

customer/templates/customer/edit.html
{% extends "erp_admin/base.html" %}
{% load static tz util %}
{% get_current_timezone as TIME_ZONE %}
{% block css %}
<style>
td span{
    font-size: 1em;
    padding: 0px;
}
.req{
  color:#FC0404!important;
  font-size:20px!important;
}
</style>
{% endblock css %}
{% block content %}
<form class="" action="{{form_url}}" method="post" id="qForm">
    <div class="blank">
        <div class="grid-form1">
            <a href="{% url 'customer:list' %}"> Cancel </a>
            <h4 style="margin-top:20px;">
                {{type}} Customer {% if type == "Edit" %}  <b>{{ customer.name }}</b>{% endif %}
            </h4>
            <div class="tab-content">
                <div class="tab-pane active" id="horizontal-form">
                    {% csrf_token %}
                    {{ customer_form.non_field_errors }}
                    {{ customer_form.field_errors }}
                    
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label">Name<span class="req">*</span></label>
                                <div class="">
                                    {{ customer_form.name.errors }}{{ customer_form.name }}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label">Phone<span class="req">*</span></label>
                                <div class="">
                                    {{ customer_form.phone }}
                                    {{ customer_form.phone.errors }}
                                </div>
                            </div>
                            
                        </div>
                         <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label">Address<span class="req">*</span></label>
                                <div class="">
                                    {{ customer_form.address }}
                                    {{ customer_form.address.errors }}
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

            <button class="btn-primary btn">Submit</button>
        </div>
    </div>
</form>

{% endblock content %}
{% block jsscript %}


{% endblock jsscript %}

customer/templates/customer/index.html
{% extends "erp_admin/base.html" %} {% load static tz %} {% get_current_timezone as TIME_ZONE %} {% block head %}
<style>
</style>
{% endblock head %} {% block content %}
<div id="app"></div>
{% endblock content %} {% block jsscript %}

<script src="{% static 'js/jquery.chained.min.js' %}"></script>
<script src="{% static 'js/bundles/vendor.bundle.js' %}"></script>
<script src="{% static 'js/bundles/customer_list.js' %}"></script>
{% endblock jsscript %}

customer/templates/customer/list.html
{% extends "erp_admin/base.html" %}{% load humanize %}
{% load static %}
{% block head %}
<style type="text/css">
.status-open {
    background-color: #2fd22f;
    font-size: 16px;
}
.status-rejected {
    background-color: red;
    font-size: 12px;
}
.fabutton {
  background: none;
  padding: 0px;
  border: none;
}
.table>thead>tr>th{
    color:#288f99!important;
    font-size: 15px!important;
    
}
</style>
{% endblock head %}
{% block content %}
    

<!-- Modal -->
<div class="modal fade" id="filter-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Filters</h4>
      </div>
      <div class="modal-body">
        <form action="" method="get">
            {# {{ filter.form }} #}

            <div class="col-sm-6">
                <div class="form-group">
                    <label class="control-label">{{ filter.form.name.label }}</label>
                    {{ filter.form.name }}
                </div>
            </div>


            <div class="clearfix"></div>


                
            <button type="submit" class="btn btn-primary pull-right">Submit</button>
            <div class="clearfix"></div>
        </form>
      </div>
      <div class="modal-footer">
        
      </div>
    </div>
  </div>
</div>
    <div class="content-main">
        <div class="block">
            <div class="row show-grid">
                <div class="col-sm-6">
                    <h3>
                        Customers
                        <a href="{% url 'customer:create' %}" class="btn btn-link">
                              <i class="fa fa-plus-square-o fa-2x"></i>
                        </a>
                    </h3>
                </div>
                <div class="col-sm-6">
                    <div class="pull-right">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#filter-modal">
                          <i class="fa fa-filter"></i> Filters
                        </button>
                        <a class="btn btn-primary btn-sm" href="{% url 'customer:list' %}">
                          <i class="fa fa-refresh"></i> Refresh
                        </a>
                        
                    </div>
                </div>                          
            </div>
            <div class="row">
                <div class="col-sm-12 table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Customer</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for customer in customers %}
                            <tr>
                                <td scope="row">{{ forloop.counter }}</td>
                                <td>
                                    <a href="{% url 'customer:detail' customer.pk %}" class="btn btn-link">
                                        {{ customer }}<br>
                                        {{ customer.contact }}
                                    </a>
                                </td>
                                
                                <td>
                                    <a href="{% url 'customer:edit' customer.pk %}" class="btn btn-link">
                                        <i class="fa fa-pencil-square-o fa-fw"></i>
                                    </a>
                                </td>
                                <td>
                                    <form class="delete" method="post" action="{% url 'customer:delete' customer.pk %}">{% csrf_token %}
                                        <button type="submit" class="fabutton">
                                            <i class="fa fa-trash-o fa-fw"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            {% empty %}
                            <tr><td colspan="4">No Customers</td></tr>
                            {% endfor %}

                        </tbody>
                    </table>

                    <div id="pagination">
                        {{pagination|safe}}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block jsscript %}
<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/daterangepicker.js' %}"></script>
<script>
$(document).ready(function(){


    $('form.delete').submit( function (e){
        e.preventDefault()
        e.stopPropagation()
        if(confirm('Do you want to Delete the entire student Details')){
            this.submit()
        }
    })


    $('[data-toggle="tooltip"]').tooltip();

    $("#pagination a").click(function(e){
        e.preventDefault()
        page_string = this.href.slice(this.href.indexOf("?") + 1)
        
        var query_string = ""   
        var search_query = window.location.search
        var query_obj = {}
        if(search_query){
            if(search_query.indexOf('?') > -1)
                search_query = search_query.substr(1)
            
            var searchQueryStrings = [search_query]
            if(search_query.indexOf('&') > -1)
                searchQueryStrings = search_query.split('&')
            
            searchQueryStrings.forEach(qs => {
                var query_array = qs.split('=')
                query_obj[query_array[0]] = query_array[1]
            })

        }
        
        query_obj['page'] = page_string.split('=')[1]
        for(var k in query_obj){
            query_string += k + '=' + query_obj[k] + '&'
        }
        
        // console.log(query_string, query_obj, window.location)
        window.location = window.location.pathname + "?" + query_string.slice(0, -1)
    })
    var format = 'YYYY-MM-DD H:mm'
    function cb(start, end) {
        $('#created_at span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        $("#id_created_at_0").val(start.format(format));
        $("#id_created_at_1").val(end.format(format));  
    }

    $('#filter-modal').on('shown.bs.modal', function () {
        console.log(moment($("#id_created_at_0").val()))
        var start_date = $("#id_created_at_0").val() ? moment($("#id_created_at_0").val()) : moment().subtract(29, 'days')
        var end_date = $("#id_created_at_1").val() ? moment($("#id_created_at_1").val()) : moment()
    
        $('#created_at').daterangepicker({
            startDate: start_date,
            endDate: end_date,
            showDropdowns: true,
            locale: {
                format: format,
            },
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            }
        }, cb);
        cb(start_date, end_date)

    })



});
</script>
{% endblock jsscript %}

customer/templates/customer/transaction_detail.html
{% extends "erp_admin/base.html" %} {% load guardian_tags %} {% block content %}

<style>
    th{
    color:#337ab7!important;
}
td{
    color:#000000!important;
}
.grouperTable{
    border-top:1px solid #d4d2d2;
    border-left:1px solid #d4d2d2;
    border-right:1px solid #d4d2d2;
}

</style>
<div class="banner">
    <h2>
        <a href="/">Home</a>
        <i class="fa fa-angle-right"></i>
        <a href="{{ request.META.HTTP_REFERER }}">Transactions </a>
        <i class="fa fa-angle-right"></i>
        <span>{{customer}}</span>
        <a href="{{ request.META.HTTP_REFERER }}" class="pull-right"><i class="fa fa-times"></i></a>
    </h2>
</div>
<div class="blank">
    <div class="blank-page">
        <div class="row show-grid">
            <div class="col-sm-12">
                <h3>
                    Asset History for <span style="color:#01788B;">{{tr_date|date:"F d, l"}}</span>
                </h3>
            </div>
        </div>


        <div class="row show-grid">
            <div class="col-sm-12 table-responsive">
                <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Time</th>
                            <th>Asset</th>
                            <th>Handover From</th>
                            <th>Handover To</th>
                            <th>Asset Status</th>
                            <th>Usage Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% regroup transactions by date_and_time.time as transaction_list %}
                        {% for transaction in transaction_list %}
                                {% for trn in transaction.list %}
                                    <tr class="grouperTable">
                                        <td class="grouper">{{transaction.grouper}}</td>
                                        <td scope="row">{{ trn.asset }}</td>
                                        <td scope="row" class="source">{{ trn.source }}</td>
                                        <td scope="row" class="destination">{{ trn.destination }}</td>
                                        {% if trn.asset_status == 'Functional' %}
                                            <td scope="row"><span class="label label-success">{{ trn.asset_status }}</span></td>
                                        {% elif trn.asset_status == 'Damage' %}
                                            <td scope="row"><span class="label label-warning">{{ trn.asset_status }}</span></td>
                                        {% elif trn.asset_status == 'Destroyed' %}
                                            <td scope="row"><span class="label label-danger">{{ trn.asset_status }}</span></td>
                                        {% endif %}

                                        {% if trn.usage_status == 'Used' %}
                                            <td scope="row"><i class="fa fa-check fa-2x" style="color:green;"></i></td>
                                        {% else %}
                                            <td scope="row"><i class="fa fa-close fa-2x" style="color:#d9534f;"></i></td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                        {% empty %}
                        <tr>
                            <td colspan="6">No Data</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
            </div>
        </div>
        <div id="pagination">
                {{pagination|safe}}
            </div>
    </div>
</div>


{% endblock content %}

{% block jsscript %}
<script>
    $(document).ready(function(){
    var seen = {};
    $('.grouper').each(function() {
      var txt = $(this).text();
      if (seen[txt]){
        $(this).html('');
        $(this).closest('tr').find('.source').html('&#12291;')
        $(this).closest('tr').find('.destination').html('&#12291;')
        $(this).parent('tr').css('border-top','1px solid white');
        $('.table tr:last').css('border-bottom','1px solid #d4d2d2')
        }
      else{
        seen[txt] = true;
        }
    });
      $("#pagination a").click(function(e){
        e.preventDefault()
        page_string = this.href.slice(this.href.indexOf("?") + 1)
        var query_string = ""
        var search_query = window.location.search
        var query_obj = {}
        if(search_query){
            if(search_query.indexOf('?') > -1)
                search_query = search_query.substr(1)

            var searchQueryStrings = [search_query]
            if(search_query.indexOf('&') > -1)
                searchQueryStrings = search_query.split('&')
            searchQueryStrings.forEach(qs => {
                var query_array = qs.split('=')
                query_obj[query_array[0]] = query_array[1]
            })
        }
        query_obj['page'] = page_string.split('=')[1]
        for(var k in query_obj){
            query_string += k + '=' + query_obj[k] + '&'
        }

        // console.log(query_string, query_obj, window.location)
        window.location = window.location.pathname + "?" + query_string.slice(0, -1)
    })
});
</script>
{% endblock jsscript %}