asset/purchase_order/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [
    url(r'^$', views.index, name="list"),
    url(r'^create/$', views.create, name="create"),
    url(r'^code/settings/$', views.code_settings, name='code_settings'),
    url(r'^mail/settings/$', views.mail_settings, name='mail_settings'),
    url(r'^(?P<pk>[^/]+)/', include([
        url(r'^edit/$', views.edit, name="edit"),
        url(r'^detail/$', views.detail, name='detail'),
        url(r"^detail.pdf/$", views.InventoryPurchaseorderPDFView.as_view(), name="download-pdf"),
        url(r'^mail/$', views.purchase_order_mail, name='mail'),
        url(r'^delete/$', views.delete, name="delete"),

    ]))
]

asset/stock/urls.py
from django.conf.urls import include, url
from . import stock, item


stock_patterns = ([
    url(r'^create/$', stock.create, name='create'),
    url(r'^code/settings/$', stock.code_settings, name='code_settings'),
    url(r'^(?P<stock_pk>[^/]+)/', include([
        url(r'^detail/$', stock.detail, name='stock_detail'),
        url(r'^edit/$', stock.edit, name='stock_edit'),
        url(r'^changeStatus/$', stock.edit_status, name='editStockStatus'),
        url(r'^items/', include([
            # url(r'^add/$', item.create, name='create'),
            url(r'^(?P<item_pk>[^/]+)/delete/$', item.delete, name='delete_item'),
            url(r'^(?P<item_pk>[^/]+)/changeStatus/$', item.edit_status, name='edit-status'),
            url(r'^(?P<item_pk>[^/]+)/edit/$', item.edit, name='edit'),
            url(r'^(?P<item_pk>[^/]+)/item_detail/$', item.item_detail, name='item_detail'),
            url(r'^', item.items, name='list'),
        ], namespace="item")),
    ])),

    # url(r'^batches/', include([
    #     url(r'^(?P<batch_pk>[^/]+)/', include([
    #         url(r'^changeStatus/$', batch.edit_status, name='edit-status'),
    #         url(r'^delete/$', batch.delete, name='delete'),
    #         url(r'^edit/$', batch.edit, name='edit'),

    #         url(r'^items/', include([
    #             url(r'^add/$', item.create, name='create'),
    #             url(r'^delete/$', item.delete, name='delete_item'),
    #             url(r'^(?P<item_pk>[^/]+)/changeStatus/$', item.edit_status, name='edit-status'),
    #             url(r'^(?P<item_pk>[^/]+)/edit/$', item.edit, name='edit'),
    #             url(r'^(?P<item_pk>[^/]+)/item_detail/$', item.item_detail, name='item_detail'),
    #             url(r'^', item.items, name='list'),
    #         ], namespace="item")),
    #     ])),
    # ], namespace="batch")),

    # url(r'^stock/batch/(?P<batch_pk>[^/]+)/edit/$', stock.edit_batch, name='edit_batch'),
    # url(r'^stock/batch/item/(?P<item_pk>[^/]+)/edit/$', stock.edit_item, name='edit_item'),

    url(r'^products/checkStock/$', stock.checkStock, name='checkStock'),
    url(r'^asset/lists/$', item.assetLists, name='assetLists'),
    url(r'^asset/staffAssetlists/$', item.staff_asset_lists, name='staff_asset_lists'),


    # # For mobile view The below links
    # # search for stock via product code- Get
    # url(r'^batch/product/(?P<code>[\w\-]+)/$', batch.batch_detail),
    # url(r'^batch/(?P<batch_pk>[^/]+)/statusBooked/$', batch.batch_status_booked),
    # url(r'^batch/(?P<batch_pk>[^/]+)/cancelBooked/$', batch.batch_cancel_booked),
    url(r'^', stock.index, name="list"),
])

asset/urls.py
from django.conf.urls import include, url
from asset import asset, asset_type
from .stock.urls import stock_patterns

app_name = "asset"

asset_type_patterns = ([
    url(r'^asset_type/', include([

        url(r'^create/$', asset_type.create, name="create"),
        url(r'^asset_category/$', asset_type.asset_category, name="asset_category"),

    ])),

], 'asset_type')


urlpatterns = [

    url(r'^asset/', include([
        url(r'^index/$', asset.index, name="list"),
        url(r'^dashboard/$', asset.dashboard, name="dashboard"),
        url(r'^create/$', asset.create, name="create"),
        url(r'^customer/asset/create/$', asset.customer_asset_create, name="customer_asset_create"),
        url(r'^customer/asset/(?P<pk>[^/]+)/edit/$', asset.customer_asset_edit, name="customer_asset_edit"),
        url(r'^(?P<pk>[^/]+)/edit/$', asset.edit, name="edit"),
        url(r'^(?P<pk>[^/]+)/detail/$', asset.detail, name="detail"),
        url(r'^(?P<pk>[^/]+)/delete/$', asset.delete, name="delete"),
        url(r'^stocks/', include(stock_patterns, namespace="stock")),
        url(r'^code/settings/$', asset.code_settings, name='code_settings'),
        url(r'^(?P<barcode>[^/]+)/transaction/$', asset.asset_transaction, name="asset_transaction"),

    ])),
    url(r'^asset/', include(asset_type_patterns)),
    url(r'^transaction/(?P<pk>[^/]+)/detail/$', asset.transaction_detail, name="transaction_detail"),
    url(r'^customer/transactions/(?P<selectedDate>[^/]+)/$', asset.customer_transaction, name="customer_transaction"),
    url(r'^customer/transactions/$', asset.customer_transaction, name="customer_transaction"),
    url(r'^customer/assets/(?P<date>[^/]+)/(?P<customer>[^/]+)/$', asset.customer_asset, name="customer_asset"),
    url(r'^asset/change/status/(?P<pk>[^/]+)/$', asset.changeStatus, name="changeStatus"),
    url(r'^employee/assets/$', asset.employee_assets, name="employee_assets"),
    url(r'^return/asset/(?P<pk>[^/]+)/$', asset.return_asset, name="return_asset"),


]

customer/urls.py
from django.conf.urls import include, url
from rest_framework import routers
from django.views.decorators.csrf import csrf_exempt
from customer import api, customer, contact, address,address_api

app_name = "customer"

# router = routers.DefaultRouter()
# router.register(r'customers', api.CustomerViewSet, base_name="customer")
# router.register(r'contacts', api.ContactViewSet, base_name="contact")
# m_router = routers.DefaultRouter()
# m_router.register(r'address', address_api.AddressCreateViewSet, base_name="contact_address")
# router.register(r'addresses', api.AddressViewSet, base_name="address")

# customer_list = api.CustomerViewSet.as_view({'get': 'list'})
# customer_create = api.CustomerViewSet.as_view({'get': 'create_form'})
# customer_retrieve = api.CustomerViewSet.as_view({'get': 'retrieve'})
# customer_edit = api.CustomerViewSet.as_view({'get': 'edit_form'})
# contact_retrieve = api.ContactViewSet.as_view({'get': 'retrieve'})
# contact_select_list = api.ContactViewSet.as_view({'get': 'select_list'})


urlpatterns = [
    # url(r'^$', views.index, name="list"),
    # url(r'^customers$', customer_list, name="customers"),
    # Customer urls
    url(r'^customers/$', customer.list, name="list"),
    url(r'^customers/create/$', customer.create, name="create"),
    url(r'^customers/(?P<pk>[^/]+)/transactions/$', customer.all_transactions, name="transactions"),
    url(r'^customers/(?P<pk>[^/]+)/$', customer.detail, name="detail"),
    url(r'^customers/(?P<pk>[^/]+)/edit/$', customer.edit, name="edit"),
    url(r'^customers/(?P<pk>[^/]+)/delete/$', customer.delete, name="delete"),

    # Contact Urls
    url(r'^contacts/(?P<pk>[^/]+)/$', contact.detail, name="contact-detail"),
    url(r'^customer/(?P<barcode>[^/]+)/new/create/$', customer.customer_new_create, name="customer_new_create"),


]


# GET api/enquiries/ => customer list
# GET api/enquiries/choices => customer choice fields
# POST api/enquiries/  => create customer
# PUT api/enquiries/{pk}  => update customer
# DELETE api/enquiries/{pk}  => delete customer

papercraneerp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from sitetree.sitetreeapp import compose_dynamic_tree, register_dynamic_trees
from erp_admin import views as erpAdminViews


# from employee import views as employeeViews
urlpatterns = [
    url(r'^$', erpAdminViews.dashboard),
    # url(r'^api-token-auth/', views.obtain_auth_token),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('employee.urls', namespace="employee")),
    url(r'^', include('customer.urls', namespace="customer")),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include('location.urls', namespace="location")),
    url(r'^company/', include('company.urls', namespace="company")),
    url(r'^', include('asset.urls', namespace="asset")),




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns = static(settings.MEDIA_URL, view=never_cache(serve_static),
#                          document_root=settings.MEDIA_ROOT) + urlpatterns
admin.site.site_header = 'Jawdrop Administration'




register_dynamic_trees(

    compose_dynamic_tree('erp_admin'),

    # or gather all the trees from `books` and attach them to `main` tree root,
    compose_dynamic_tree('employee'),
    compose_dynamic_tree('customer'),
    compose_dynamic_tree('asset'),





)

asset/models.py
from django.db import models

from customer.models import Customer
from employee.models import Employee
from erp_core.models import ErpAbstractBaseModel



class AssetBaseModel(ErpAbstractBaseModel):

    code = models.CharField(max_length=255, null=True, blank=True,unique=True)
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)

    class Meta:
        abstract = True

    # def save(self, *args, **kwargs):
    #     if self.code and self.created_at is None:
    #         CodeSetting.incrementCountIndex()
    #
    #     return super(AssetBaseModel, self).save(*args, **kwargs)


class AssetType(ErpAbstractBaseModel):

    name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.name)


class AssetCategory(ErpAbstractBaseModel):

    name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.name)


# class DahlBookManager(models.Manager):
#     def get_queryset(self):
#         return super(DahlBookManager, self).get_queryset().filter(author='Roald Dahl')


class FixedAssetManager(models.Manager):
    def get_queryset(self):
        return super(FixedAssetManager, self).get_queryset().filter(customer_asset=False)


class Asset(AssetBaseModel):
    CHOICES = (
        ('sq.feet', 'sq.feet'),
        ('hours', 'hours'),
    )

    objects = models.Manager()
    asset_type = models.ForeignKey(AssetType)
    asset_category = models.ForeignKey(AssetCategory,null=True)
    manufacturing_date=models.DateField(null=True)
    expiry_date=models.DateField(null=True)
    returnable=models.BooleanField(default=True)
    warranty=models.BooleanField(default=True)
    warranty_duration=models.CharField(max_length=30,null=True,blank=True)
    used=models.BooleanField(default=False)
    available=models.BooleanField(default=True)


    def __str__(self):
        return str(self.name)


class AssetTransaction(ErpAbstractBaseModel):
    STATUS_DAMAGE = 'Damage'
    STATUS_DESTROYED = 'Destroyed'
    STATUS_FUNCTIONAL = 'Functional'
    STATUS_USED = 'Used'
    STATUS_NOTUSED = 'Not Used'

    ASSET_STATUS = (
        (STATUS_DAMAGE, "Damage"),
        (STATUS_DESTROYED, "Destroyed"),
        (STATUS_FUNCTIONAL, "Functional"),


    )

    USAGE_STATUS = (
        (STATUS_USED, 'Used'),
        (STATUS_NOTUSED, 'Not Used'),
    )

    asset=models.ForeignKey(Asset,related_name="asset")
    customer=models.ForeignKey(Customer,related_name="transactions")
    date_and_time=models.DateTimeField()
    source=models.ForeignKey(Employee,related_name="source")
    destination=models.ForeignKey(Employee,null=True,related_name="destination",blank=True)
    created_by=models.ForeignKey(Employee,related_name="created_by")
    updated_by=models.ForeignKey(Employee,related_name="updated_by")
    asset_status=models.CharField(max_length=15,choices=ASSET_STATUS,default=STATUS_FUNCTIONAL)
    usage_status=models.CharField(max_length=15,choices=USAGE_STATUS,default=STATUS_NOTUSED)
    parent = models.ForeignKey('self',null=True,related_name="predecessors",blank=True)

    def __str__(self):
        return str(self.asset)+str(self.date_and_time)

asset/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Asset, AssetType, AssetTransaction


class AssetForm(ModelForm):
    class Meta:
        model = Asset

        fields = ['name','asset_category','asset_type','manufacturing_date','expiry_date','warranty_duration','warranty','returnable']

        widgets = {

            "name": forms.TextInput(attrs={'class': "form-control", 'required': "required"}),
            "asset_category": forms.Select(attrs={'class': "form-control", 'required': "required"}),
            "asset_type": forms.Select(attrs={'class': "form-control", 'required': "required"}),
            "manufacturing_date": forms.DateInput(attrs={'class': "form-control tdate", 'required': "required"}),
            "expiry_date": forms.DateInput(attrs={'class': "form-control tdate", 'required': "required"}),
            "warranty_duration": forms.TextInput(attrs={'class': "form-control"}),
            "warranty": forms.CheckboxInput(),
            "returnable": forms.CheckboxInput(),

        }


class CustomerAssetForm(ModelForm):
    class Meta:
        model = Asset

        exclude = ['code','location']

        widgets = {

            "name": forms.TextInput(attrs={'class': "form-control", 'required': "required"}),
            # "code": forms.TextInput(attrs={'class': "form-control", 'required': "required"}),
            "price": forms.NumberInput(attrs={'class': "form-control", }),
            "asset_type": forms.Select(attrs={'class': 'form-control', "multiple": False}),
            # "location": forms.Select(attrs={'id': "location", 'class': 'form-control', "multiple": False}),
            # "own_asset": forms.CheckboxInput(),
            # "rent_asset": forms.CheckboxInput(),
            # "customer_asset": forms.CheckboxInput(),
            "price_based_on": forms.Select(attrs={'class': 'form-control', "multiple": False}),
            # "staff_asset": forms.CheckboxInput(),

        }


class AssetTypeForm(ModelForm):
    class Meta:
        model = AssetType
        fields = ('name',)
        widgets = {

            "name": forms.TextInput(attrs={'class': "form-control"}),
        }



class TransactionForm(ModelForm):
    class Meta:
        model = AssetTransaction
        fields = ('customer','date_and_time','source','destination','parent')
        widgets = {

            "customer": forms.Select(attrs={'class': "form-control",'required': "required"}),
            "source": forms.Select(attrs={'class': "form-control",'required': "required"}),
            "destination": forms.Select(attrs={'class': "form-control"}),
            "parent": forms.Select(attrs={'class': "form-control", }),
            "date_and_time": forms.DateInput(attrs={'class': "form-control tdate"}),

        }

asset/views.py
from django.shortcuts import render

# Create your views here.

asset/templates/asset/category_dashboard.html
{% extends "erp_admin/base.html" %} {% block content %}
    {% load staticfiles %}
    {% block head %}
        <link href="{% static 'css/box_style.css' %}" rel='stylesheet' type='text/css' />
        <style>
            .white{
            color:#ffffff;
            }
        </style>
    {% endblock head %}
    <div class="blank">
        <div class="blank-page">
            <div class="row show-grid" style="margin-bottom:300px;">
                <div class="col-sm-12 col-md-12 col-xs-12">
                    <h2>Asset List</h2>

                    <div class="row" style="margin-top:30px;">

                        <div class="col-sm-4 col-md-4 col-xs-12">
                            <div class="border_style bg3" align="center">
                                <a href="{% url 'asset:create' %}">
                                    <span class='white'>Add Asset</span>
                                    <div>
                                        <span class="white"><i class="fa fa-plus fa-2x"></i></span>
                                    </div>
                                </a>
                            </div>
                            
                        </div>




                   
                </div>
                
            </div>
        </div>
    </div>
    
    
{% endblock content %}

asset/templates/asset/index.html
{% extends "erp_admin/base.html" %}{% load humanize %}
{% load static %}
{% block head %}
<style type="text/css">

.fabutton {
  background: none;
  padding: 0px;
  border: none;
}
</style>
{% endblock head %}
{% block content %}

<div class="modal fade" id="filter-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Filters</h4>
      </div>
      <div class="modal-body">
        <form action="" method="get">
            {# {{ filter.form }} #}
           
            <div class="col-sm-6">
                <div class="form-group">
                    <label class="control-label">{{ filter.form.name.label }}</label>
                    {{ filter.form.name }}
                </div>
            </div>
             <div class="col-sm-6">
                <div class="form-group">
                    <label class="control-label">{{ filter.form.asset_type.label }}</label>
                    {{ filter.form.asset_type }}
                </div>
            </div>

            

            <!--<div class="col-sm-12">
                <div class="form-group">
                    <label class="control-label">{{ filter.form.created_at.label }}</label>
                    {{ filter.form.created_at }}
                    <div id="created_at" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%;">
                        <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>&nbsp;
                        <span>{% if from_date %}{{from_date}}-{{to_date}} {% else %} {{today|date:"F"}} {{today|date:"Y"}} {% endif %}</span><b class="caret"></b>
                    </div>
                </div>
            </div>-->
            <div class="clearfix"></div>
            <h4 style="padding: 10px;">Sort By</h4>
            <div class="col-sm-12">
                <div class="form-group">
                    <label class="control-label">{{ filter.form.order_by_created_at.label }}</label>
                    {{ filter.form.order_by_created_at }}
                </div>
            </div>
            
                
            <button type="submit" class="btn btn-primary pull-right">Submit</button>
            <div class="clearfix"></div>
        </form>
      </div>
      <div class="modal-footer">
        
      </div>
    </div>
  </div>
</div>
	
	<div class="content-main">
		<div class="block">
			<div class="row show-grid">
				<div class="col-sm-6">

					<h3>
					Assets
					<a href="{% url 'asset:create' %}" class="btn btn-link">
						<i class="fa fa-plus-square-o fa-2x"></i>
					</a>
					</h3>
				</div>
				<div class="col-sm-6">
					<div class="pull-right">
						<!-- Button trigger modal -->
						<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#filter-modal">
							<i class="fa fa-filter"></i>
						Filters
						</button>
						<a href="{% url 'asset:list' %}" class="btn btn-primary btn-sm"><i class="fa fa-refresh"></i> Refresh</a>
						
						
						
					</div>
				</div>
			</div>
			<div class="row show-grid">
				<div class="col-sm-12">
                    <div class="table-responsive">

						<table class="table table-striped">
							<thead>
								<tr>
									
								</tr>
							</thead>
							<tbody>
								{% for asset in assets %}
									<tr>
										<td scope="row">{{ forloop.counter }}</td>
										<td><a href="{% url 'asset:detail' asset.pk %}">{{asset.name}}</td>
										<td>
		                                    <a href="{% url 'asset:detail' asset.pk %}" class="btn btn-link">
		                                        <i class="fa fa-eye"></i>
		                                    </a>
		                                </td>
		                                <td>
                                            {% if asset.customer_asset %}
                                                <a href="{% url 'asset:customer_asset_edit' asset.pk %}" class="btn btn-link">
                                                    <i class="fa fa-pencil-square-o fa-fw"></i> 
                                                </a>
                                            {% else %}
    		                                    <a href="{% url 'asset:edit' asset.pk %}" class="btn btn-link">
    		                                        <i class="fa fa-pencil-square-o fa-fw"></i> 
    		                                    </a>
                                            {% endif %}
		                                </td>
                                       
		                                <td>
											<form class="delete" method="post" action="{% url 'asset:delete' asset.pk %}">{% csrf_token %}
												<button type="submit" class="fabutton">
													<i class="fa fa-trash-o fa-fw"></i>
												</button>
                                			</form>

		                                </td>
										
									</tr>
									{% empty %}
									<tr><td>No Assets</td></tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
					<div id="pagination">
						{{pagination|safe}}
					</div>
					
				</div>
			</div>
		</div>
	</div>
{% endblock content %}
{% block jsscript %}

<script>
$(document).ready(function(){
    

   $('form.delete').submit( function (e){
        e.preventDefault()
        e.stopPropagation()
        if(confirm('Do you want to Delete the entire student Details')){
            this.submit()
        }
    })
});
</script>

{% endblock jsscript %}

asset/templates/asset/staff_asset_type_list.html
{% extends "erp_admin/base.html" %}{% load humanize %}
{% load static %}
{% block head %}
<style type="text/css">

.fabutton {
  background: none;
  padding: 0px;
  border: none;
}
</style>
{% endblock head %}
{% block content %}

<div class="modal fade" id="filter-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Filters</h4>
      </div>
      <div class="modal-body">
        <form action="" method="get">
            {# {{ filter.form }} #}
            <div class="col-sm-6">
                <div class="form-group">
                    <label class="control-label">{{ filter.form.code.label }}</label>
                    {{ filter.form.code }}
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label class="control-label">{{ filter.form.name.label }}</label>
                    {{ filter.form.name }}
                </div>
            </div>
             <div class="col-sm-6">
                <div class="form-group">
                    <label class="control-label">{{ filter.form.asset_type.label }}</label>
                    {{ filter.form.asset_type }}
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label class="control-label">{{ filter.form.own_asset.label }}</label>
                    {{ filter.form.own_asset }}
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label class="control-label">{{ filter.form.rent_asset.label }}</label>
                    {{ filter.form.rent_asset }}
                </div>
            </div>
             <div class="col-sm-6">
                <div class="form-group">
                    <label class="control-label">{{ filter.form.customer_asset.label }}</label>
                    {{ filter.form.customer_asset }}
                </div>
            </div>
            

            <!--<div class="col-sm-12">
                <div class="form-group">
                    <label class="control-label">{{ filter.form.created_at.label }}</label>
                    {{ filter.form.created_at }}
                    <div id="created_at" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%;">
                        <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>&nbsp;
                        <span>{% if from_date %}{{from_date}}-{{to_date}} {% else %} {{today|date:"F"}} {{today|date:"Y"}} {% endif %}</span><b class="caret"></b>
                    </div>
                </div>
            </div>-->
            <div class="clearfix"></div>
            <h4 style="padding: 10px;">Sort By</h4>
            <div class="col-sm-12">
                <div class="form-group">
                    <label class="control-label">{{ filter.form.order_by_created_at.label }}</label>
                    {{ filter.form.order_by_created_at }}
                </div>
            </div>
            
                
            <button type="submit" class="btn btn-primary pull-right">Submit</button>
            <div class="clearfix"></div>
        </form>
      </div>
      <div class="modal-footer">
        
      </div>
    </div>
  </div>
</div>
	
	<div class="content-main">
		<div class="block">
			<div class="row show-grid">
				<div class="col-sm-6">
                <a style="padding-left: 5px;" href="{% url 'asset:dashboard' %}">Back to Dashboard</a>
					<h3>
					Staff Assets
					<a href="{% url 'asset:create' %}" class="btn btn-link">
						<i class="fa fa-plus-square-o fa-2x"></i>
					</a>
					</h3>
				</div>
				<div class="col-sm-6">
					<div class="pull-right">
						<!-- Button trigger modal -->
						<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#filter-modal">
						Apply Filters
						</button>
						<a href="{% url 'asset:list' %}" class="btn btn-primary">Refresh</a>
						
						
						
					</div>
				</div>
			</div>
			<div class="row show-grid">
				<div class="col-sm-12">
                    <div class="table-responsive">

						<table class="table table-striped">
							<thead>
								<tr>
									
								</tr>
							</thead>
							<tbody>
								{% for asset in assets %}
									<tr>
										<td scope="row">{{ forloop.counter }}</td>
										<td><a href="{% url 'asset:staff_asset_detail' asset.pk %}">{{asset.name}}({{asset.code}})</td>
										<td>
		                                    <a href="{% url 'asset:staff_asset_detail' asset.pk %}" class="btn btn-link">
		                                        <i class="fa fa-eye"></i>
		                                    </a>
		                                </td>
		                                <td>
		                                    <a href="{% url 'asset:edit' asset.pk %}" class="btn btn-link">
		                                        <i class="fa fa-pencil-square-o fa-fw"></i> 
		                                    </a>
		                                </td>
                                       
		                                <td>
		                                    <form method="post" action="{% url 'asset:delete' asset.pk %}" onsubmit="remove(this, event)">
		                                        {% csrf_token %}
		                                        <button type="submit" class="fabutton">
		                                            <i class="fa fa-trash-o fa-fw"></i> 
		                                        </button>
		                                    </form>
		                                </td>
										
									</tr>
									{% empty %}
									<tr><td>No Assets</td></tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
					<div id="pagination">
						{{pagination|safe}}
					</div>
					
				</div>
			</div>
		</div>
	</div>
{% endblock content %}
{% block jsscript %}

<script>
$(document).ready(function(){
    

    function remove(form, e){
        e.preventDefault()
        if(confirm('Confirm Delete')){
            form.submit()
        }
    }

});
</script>

{% endblock jsscript %}