asset/urls.py
from django.conf.urls import include, url
from asset import asset, asset_type
from .stock.urls import stock_patterns

app_name = "asset"

asset_type_patterns = ([
    url(r'^asset_type/', include([

        url(r'^create/$', asset_type.create, name="create"),
        url(r'^asset_category/$', asset_type.asset_category, name="asset_category"),

    ])),

], 'asset_type')


urlpatterns = [

    url(r'^asset/', include([
        url(r'^index/$', asset.index, name="list"),
        url(r'^dashboard/$', asset.dashboard, name="dashboard"),
        url(r'^create/$', asset.create, name="create"),
        url(r'^customer/asset/create/$', asset.customer_asset_create, name="customer_asset_create"),
        url(r'^customer/asset/(?P<pk>[^/]+)/edit/$', asset.customer_asset_edit, name="customer_asset_edit"),
        url(r'^(?P<pk>[^/]+)/edit/$', asset.edit, name="edit"),
        url(r'^(?P<pk>[^/]+)/detail/$', asset.detail, name="detail"),
        url(r'^(?P<pk>[^/]+)/delete/$', asset.delete, name="delete"),
        url(r'^stocks/', include(stock_patterns, namespace="stock")),
        url(r'^code/settings/$', asset.code_settings, name='code_settings'),
        url(r'^(?P<barcode>[^/]+)/transaction/$', asset.asset_transaction, name="asset_transaction"),

    ])),
    url(r'^asset/', include(asset_type_patterns)),
    url(r'^transaction/(?P<pk>[^/]+)/detail/$', asset.transaction_detail, name="transaction_detail"),
    url(r'^customer/transactions/(?P<selectedDate>[^/]+)/$', asset.customer_transaction, name="customer_transaction"),
    url(r'^customer/transactions/$', asset.customer_transaction, name="customer_transaction"),
    url(r'^customer/assets/(?P<date>[^/]+)/(?P<customer>[^/]+)/$', asset.customer_asset, name="customer_asset"),
    url(r'^asset/change/status/(?P<pk>[^/]+)/$', asset.changeStatus, name="changeStatus"),
    url(r'^employee/assets/$', asset.employee_assets, name="employee_assets"),
    url(r'^return/asset/(?P<pk>[^/]+)/$', asset.return_asset, name="return_asset"),


]

employee/urls.py
from django.conf.urls import include, url

from employee import views, api

app_name = "employee"


urlpatterns = [
    url(r'^employee/', include([
        url(r'^$', views.index, name="list"),
        url(r'^select_list/$', views.select2_list, name="select_list"),
        url(r'^select_employee/$', views.select_employee, name="select_employee"),
        url(r'^select_designation/$', views.select_designation, name="select_designation"),
        url(r'^create/$', views.create, name='create'),
        url(r'^(?P<pk>[^/]+)/edit/', views.edit, name='edit'),
        url(r'^(?P<pk>[^/]+)/delete/', views.delete, name='delete'),
        url(r'^(?P<pk>[^/]+)/profile/', views.profile, name='profile'),
        url(r'^incentive/list/$', views.incentive_list, name='incentive_list'),
        url(r'^incentive/list/(?P<from_date>[-\w]+)/(?P<to_date>[-\w]+)/$', views.incentive_list, name="incentiveList"),
        url(r'^(?P<pk>[^/]+)/incentive/$', views.incentives, name='incentives'),
        url(r'^(?P<pk>[^/]+)/incentive/(?P<from_date>[-\w]+)/(?P<to_date>[-\w]+)/$', views.incentives, name="incentives"),
        url(r'^findoffice/', views.select_office, name="select_office"),
        # url(r'^(?P<employee_pk>[^/]+)/todo/', include('todo.urls', namespace="todo")),
        url(r'^(?P<pk>[^/]+)/addtargets/', views.add_targets, name='add_targets'),
        url(r'^(?P<pk>[^/]+)/targets/', views.view_targets, name='view_targets'),
        url(r'^(?P<pk>[^/]+)/editTarget/(?P<target_pk>[^/]+)/$', views.edit_targets, name='edit_targets'),
        url(r'^batterystatus/create/$', api.CreateBatteryStatus, name="CreateBatteryStatus"),
        url(r'^(?P<pk>[^/]+)/timesheet/(?P<from_date>[-\w]+)/(?P<to_date>[-\w]+)/$', views.timesheet, name='timesheet_withdate'),
        url(r'^(?P<pk>[^/]+)/timesheet/', views.timesheet, name='timesheet'),
        url(r'^(?P<pk>[^/]+)/report/$', views.my_report, name="my_report"),
        url(r'^(?P<pk>[^/]+)/report/(?P<from_date>[-\w]+)/(?P<to_date>[-\w]+)/$',
            views.my_report, name="my_report_with_range"),


    ])),
    url(r'^api/employee/select_list/$', views.select2_list, name="select_list"),

]

papercraneerp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from sitetree.sitetreeapp import compose_dynamic_tree, register_dynamic_trees
from erp_admin import views as erpAdminViews


# from employee import views as employeeViews
urlpatterns = [
    url(r'^$', erpAdminViews.dashboard),
    # url(r'^api-token-auth/', views.obtain_auth_token),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('employee.urls', namespace="employee")),
    url(r'^', include('customer.urls', namespace="customer")),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include('location.urls', namespace="location")),
    url(r'^company/', include('company.urls', namespace="company")),
    url(r'^', include('asset.urls', namespace="asset")),




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns = static(settings.MEDIA_URL, view=never_cache(serve_static),
#                          document_root=settings.MEDIA_ROOT) + urlpatterns
admin.site.site_header = 'Jawdrop Administration'




register_dynamic_trees(

    compose_dynamic_tree('erp_admin'),

    # or gather all the trees from `books` and attach them to `main` tree root,
    compose_dynamic_tree('employee'),
    compose_dynamic_tree('customer'),
    compose_dynamic_tree('asset'),





)

employee/models.py
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from address.models import *
from company.models import *
from erp_core.models import ErpAbstractBaseModel
from location.models import Location
from company.models import BasicPayDaily
from django.core.validators import MinValueValidator


class AddressForEmployee(Address):
    employee = models.OneToOneField(
        'Employee', on_delete=models.CASCADE, related_name="employee_address")

    def __str__(self):
        return str(self.employee)


class ContactForEmployee(Contact):
    employee = models.OneToOneField(
        'Employee', on_delete=models.CASCADE, related_name="employee_contact")

    def __str__(self):
        return str(self.employee)


class Employee(ErpAbstractBaseModel):
    SEX = (
        ('Female', 'Female'),
        ('Male', 'Male'),
    )

    MARITALSTATUS = (
        ('Single', 'Single'),
        ('Married', 'Married'),
    )

    BLOODGROUP = (
        ('A+', 'A+'),
        ('A-', 'A-'),
        ('AB+', 'AB+'),
        ('AB-', 'AB-'),
        ('B+', 'B+'),
        ('B-', 'B-'),
        ('O+', 'O+'),
        ('O-', 'O-'),
    )
    code = models.CharField(max_length=255, unique=True)
    photo = models.FileField(upload_to='prof/%Y/%m/%d', blank=True, null=True)
    dob = models.DateField()
    gender = models.CharField(max_length=8, choices=SEX)
    marital_status = models.CharField(max_length=10, choices=MARITALSTATUS)
    blood_group = models.CharField(max_length=3, choices=BLOODGROUP)
    languages_known = models.CharField(max_length=255)
    birth_place = models.CharField(max_length=100, blank=True, null=True)
    cast = models.CharField(max_length=100, null=True, blank=True)
    religion = models.CharField(max_length=100)
    citizenship = models.CharField(max_length=100)
    status = models.BooleanField(default=True)

    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)

    primary_designation = models.ForeignKey(
        Designation, on_delete=models.CASCADE)

    secondary_designation = models.ManyToManyField(
        Designation, related_name="employee_secondary_designation", blank=True)

    reporting_officer = models.ForeignKey(
        'employee.Employee', on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        permissions = (
            ("view_employee_list", "Can view employee list"),
            ("view_employee_details", "Can view employee details"),
            ("can_access", "Can access Employee Section"),
            ("reporting_officier", "I am a reporting officier"),
            ("is_support","Support")
        )

    def get_absolute_url(self):
        return reverse('employee:profile', args=[self.code])

    def __str__(self):
        return str(self.user.first_name) + " (" + str(self.code) + ")"


class EmployeeCode(ErpAbstractBaseModel):

    character_set = models.CharField(max_length=100)


class Targets(ErpAbstractBaseModel):
    amount = models.DecimalField(max_digits=50, decimal_places=2)
    employee = models.ForeignKey(Employee)
    from_date = models.DateField(null=True, blank=True)
    to_date = models.DateField(null=True, blank=True)
    incentive_amount = models.DecimalField(
        max_digits=200, decimal_places=2, null=True, blank=True, validators=[MinValueValidator(0)])
    percentage = models.IntegerField(default=0, validators=[MinValueValidator(0)])

    def __str__(self):
        return str(self.employee) + "-" + " from " + str(self.from_date) + " to " + str(self.to_date)

    # class Meta:
    #     unique_together = ("from_date", "to_date")

    # def unique_error_message(self, model_class, unique_check):
    #     print(model_class)
    #     import pdb; pdb.set_trace()
    #     if model_class == type(self) and unique_check == ("employee", "from_date", "to_date"):
    #         return 'My custom error message'
    #     else:
    #         return super(Targets, self).unique_error_message(model_class, unique_check)

# class Incentive(ErpAbstractBaseModel):
#     target = models.OneToOneField(Targets,related_name='target_incentive')
#     def __str__(self):
#         return str(self.target)


class Batterystatus(ErpAbstractBaseModel):
    employee = models.ForeignKey(Employee)
    date_and_time = models.DateTimeField()
    level = models.PositiveIntegerField()

    def __str__(self):
        return str(self.employee)


class Bonus(ErpAbstractBaseModel):
    name = models.CharField(max_length=255, unique=True)
    amount = models.DecimalField(max_digits=20, decimal_places=2, validators=[MinValueValidator(0)])

    def __str__(self):
        return str(self.name)


class DistanceTraveled(models.Model):
    distance = models.DecimalField(max_digits=20, decimal_places=2, validators=[MinValueValidator(0)])
    date = models.DateField()
    employee = models.ForeignKey(Employee)

    class Meta:
        unique_together = ("date", "employee")

    def __str__(self):
        return str(self.employee)

employee/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Targets
from location.models import *
from employee.models import Employee, AddressForEmployee, ContactForEmployee
# from django.core.exceptions import NON_FIELD_ERRORS


class UserForm(UserCreationForm):
  class Meta:
    model = User
    widgets = {"username": forms.TextInput(attrs={'class': "form-control1", 'required': "required"}),
               "email": forms.TextInput(attrs={'class': "form-control1", 'type': "email", 'required': "required"}),
               "first_name": forms.TextInput(attrs={'class': "form-control1", 'required': "required"}),
               "password1": forms.TextInput(attrs={'class': "form-control1", 'id': "exampleInputPassword1", 'placeholder': "Password"}),
               "password2": forms.TextInput(attrs={'class': "form-control1", 'required': "required", 'placeholder': "Password"}),
               }
    fields = ['username', 'email', 'first_name', 'password1', 'password1']


class UserEditForm(UserChangeForm):
  class Meta:
    model = User
    widgets = {"username": forms.TextInput(attrs={'class': "form-control1"}),
               "email": forms.TextInput(attrs={'class': "form-control1", 'type': "email"}),
               "first_name": forms.TextInput(attrs={'class': "form-control1", 'required': "required"}),
               "password": forms.TextInput(attrs={'class': "form-control1"}),
               }
    fields = ['username', 'email', 'first_name', 'password']


class EmployeeForm(ModelForm):

  reporting_officer = forms.ModelChoiceField(
      required=False,
      label="Reports To",
      queryset=Employee.objects.none(),
      widget=forms.Select(attrs={'class': 'form-control', 'width': "100%"}),
  )

  class Meta:
    model = Employee
    widgets = {"code": forms.TextInput(attrs={'class': "form-control1", 'required': "required", 'id': "code"}),
               "dob": forms.DateInput(attrs={'class': "form-control1", "id": "pldate"}),
               "gender": forms.Select(attrs={'class': "form-control1", "data-toggle": "select"}),
               "marital_status": forms.Select(attrs={'class': "form-control1", "data-toggle": "select"}),
               "blood_group": forms.Select(attrs={'class': "form-control1", "data-toggle": "select"}),
               "languages_known": forms.TextInput(attrs={'class': "form-control1"}),
               # "birth_place": forms.TextInput(attrs={'class': "form-control1", 'required': "required"}),
               "citizenship": forms.TextInput(attrs={'class': "form-control1", 'required': "required"}),
               # "cast": forms.TextInput(attrs={'class': "form-control1", }),
               # "religion": forms.TextInput(attrs={'class': "form-control1", 'required': "required"}),
               "photo": forms.FileInput(attrs={'class': "form-control1"}),
               "primary_designation": forms.Select(attrs={'class': "form-control1", "data-toggle": "select", 'required': "required"}),
               "secondary_designation": forms.SelectMultiple(attrs={'class': "form-control1", "data-toggle": "select", "id": "secondary_desig", 'multiple': "TRUE"}),
               #"reporting_officer": forms.SelectMultiple(attrs={'class': "form-control1", "data-toggle": "select",'multiple': "TRUE"}),

               }
    fields = ['code', 'dob', 'gender', 'marital_status', 'blood_group', 'languages_known', 
              'citizenship','photo', 'primary_designation', 'secondary_designation', 'reporting_officer']

  def __init__(self, *args, **kwargs):
    # manager_qs = kwargs.pop('manager_qs')
    super(EmployeeForm, self).__init__(*args, **kwargs)
    self.set_reporting_officer_queryset()

  def set_reporting_officer_queryset(self):
    # print(self.data)
    if self.instance.id:
      self.fields['reporting_officer'].queryset = Employee.objects.filter(id=self.instance.reporting_officer_id)
    if self.data:
      if self.data['reporting_officer']:
        self.fields['reporting_officer'].queryset = Employee.objects.filter(id=self.data['reporting_officer'])


class UserChangeForm(UserChangeForm):
  class Meta:
    model = User
    fields = ('username', 'email', 'password', 'first_name')


class AddressForEmployeeForm(ModelForm):
  class Meta:
    model = AddressForEmployee

    widgets = {"addressline1": forms.TextInput(attrs={'class': "form-control1", }),
               "addressline2": forms.TextInput(attrs={'class': "form-control1"}),
               "area": forms.TextInput(attrs={'class': "form-control1", }),
               "zipcode": forms.NumberInput(attrs={'class': "form-control1", }),
               "city": forms.Select(attrs={'class': "chained form-control1", }),
               "state": forms.Select(attrs={'class': "chained form-control1", }),
               "country": forms.Select(attrs={'class': "chained form-control1",}),
               }
    fields = ['addressline1', 'addressline2', 'area', 'zipcode', 'city', 'state', 'country']


class ContactForEmployeeForm(ModelForm):
  class Meta:
    model = ContactForEmployee

    widgets = {"phone": forms.NumberInput(attrs={'class': "form-control1", 'required': "required"}),
               "alternate_phone": forms.NumberInput(attrs={'class': "form-control1", }),
               }
    fields = ['phone', 'alternate_phone']


class TargetsForm(ModelForm):
  class Meta:
    model = Targets

    widgets = {

        "amount": forms.NumberInput(attrs={'class': "form-control1", 'required': "required"}),
        "from_date": forms.DateInput(attrs={'class': "form-control1 tdate", "type": "text", 'required': "required"}),
        "to_date": forms.DateInput(attrs={'class': "form-control1 tdate", "type": "text", 'required': "required"}),
        "percentage": forms.NumberInput(attrs={'class': "form-control1", 'required': "required"}),

    }
    fields = ['amount', 'from_date', 'to_date', 'percentage']
    # error_messages = {
    #     NON_FIELD_ERRORS: {
    #         'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
    #     }
    # }

employee/templates/employee/index.html
{% extends "erp_admin/base.html" %}
{% load guardian_tags %}
{% block head %}

<style>

.table>thead>tr>th{
    color:#288f99!important;
    font-size: 15px!important;

}
</style>
{% endblock head %}

{% block content %}
<div class="blank">
    <div class="blank-page">
        <div class="row show-grid">
            <div class="col-sm-12">
                <h3>Employees

                        <a href="{% url 'employee:create' %}" class="btn btn-link">
                              <i class="fa fa-plus-square-o fa-2x"></i>
                        </a>
                </h3>


            </div>
        </div>
        <div class="row show-grid">
            <div class="col-sm-12 table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Edit</th>
                            <th>Delete</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for employee in employees %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>

                              <a href="{% url 'employee:profile' employee.code %}">
                               {{employee}}
                               </a>
                            </td>


                            {% if perms.employee.change_employee %}
                            <td>
                                 <a href="{% url 'employee:edit' employee.code %}">
                                <i class="fa fa-edit"></i>
                                </a>
                            </td>
                            {% endif %}
                            {% if perms.employee.delete_employee %}
                            <td>

                                <form class="delete" method="post" action="{% url 'employee:delete' employee.code %}">{% csrf_token %}
                                        <button type="submit" class="fabutton">
                                            <i class="fa fa-trash-o fa-fw"></i>
                                        </button>
                                    </form>

                            </td>
                            {% endif %}
                        </tr>

                        {% empty %}
                        <tr>
                            <td colspan="4">No Employees in System</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock content %}


{% block jsscript %}

<script>
$(document).ready(function(){

$('form.delete').submit( function (e){
        e.preventDefault()
        e.stopPropagation()
        if(confirm('Do you want to Delete the entire student Details')){
            this.submit()
        }
    })


  });
</script>
{% endblock jsscript %}

employee/templates/employee/profile.html
{% extends "erp_admin/base.html" %}
{% block title %} Profile{% endblock title %}
{% block content %}
<style>
.btn{
text-align: left!important;
}
.cl{
padding:30px;
border: 1px solid rgb(234, 234, 234);
margin-left:3px;
}
.cl1{
padding:20px;
border: 1px solid rgb(234, 234, 234);
margin-left:20px;
margin-right:20px;
margin-top:0px!important;
}
.profile-bottom{
width:100%!important;
margin-bottom:0px!important;
}
.profile {
min-height: 430px!important;
}
</style>
<div class="blank">
    <div class="blank-page">
        <div class="row">
            <div class="col-xs-12 col-sm-3">
                <h2></h2>
                {% if request.user.is_superuser %}<a href="{% url 'employee:list' %}" >Back</a>{% endif %}
            </div>
            <!-- Example split danger button -->

        </div>
        <div class=" profile">

		<div class="profile-bottom">
			<h3><i class="fa fa-user"></i>Profile</h3>
			<div class="profile-bottom-top">
			<div class="col-md-4 profile-bottom-img">
				<img src="images/pr.jpg" alt="">
			</div>
			<div class="col-md-8 profile-text">
				<h6>{{employee.user.first_name}}</h6>
				<table>
				<tr><td>Designation</td>
				<td>:</td>
				<td>{{employee.primary_designation.name}}</td></tr>

				<tr>
				<td>Email</td>
				<td> :</td>
				<td><a href="{{employee.user.email}}">{{employee.user.email}}</a></td>
				</tr>

				<tr>
				<td>Country </td>
				<td>:</td>
				<td> {{employee.employee_address.country}}</td>
				</tr>
				</table>
			</div>
			<div class="clearfix"></div>
			</div>
			<div class="profile-bottom-bottom">

			<div class="col-md-4 profile-fo">

				<a href="#" class="pro"><i class="fa fa-home"></i>Personal Details</a>
			</div>
			<div class="col-md-4 profile-fo">

				<a href="#" class="pro1"><i class="fa fa-phone"></i>Contact Details</a>
			</div>
			<div class="col-md-4 profile-fo">

				<a href="#"><i class="fa fa-building-o"></i>Company Details</a>
			</div>
			<div class="clearfix"></div>
			</div>
			<div class="profile-btn">

                <a class="btn btn-primary pull-right" href="{% url 'employee:edit' employee.code %}" class="btn bg-red"><i class="fa fa-edit"></i> Edit</a>
           <div class="clearfix"></div>
			</div>


		</div>
	</div>


    <div class="row cl1" style="display:none;">
        <div class="">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse1"><h3>Personal Details</h3></a>
                            </h4>
                        </div>
                        <div id="collapse1" class="panel-collapse collapse">
                            <div class="panel-body">Date Of Birth :{{employee.dob|date:'d/m/y'}}</div>
                            <div class="panel-body">Gender : {{employee.gender}}</div>
                            <div class="panel-body">Marital Status : {{employee.marital_status}}</div>
                            <div class="panel-body">Blood Group : {{employee.blood_group}}</div>
                            <div class="panel-body">Languages known : {{employee.languages_known}}</div>
                            <!--<div class="panel-body">Birth Place : {{employee.birth_place}}</div>-->
                            <!--<div class="panel-body">Cast : {{employee.cast}}</div>
                            <div class="panel-body">Religion : {{employee.religion}}</div>-->
                            <div class="panel-body">Citizenship : {{employee.citizenship}}</div>
                        </div>
                    </div>
                </div>
                
            </div>
            
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse2"><h3>Contact Details</h3></a>
                            </h4>
                        </div>
                        <div id="collapse2" class="panel-collapse collapse">
                            <div class="panel-body">
                                Contact Address
                            </div>
                            <div class="panel-body">
                                <address>
                                    {{employee.employee_address.addressline1}},
                                    {{employee.employee_address.addressline2}}</br>
                                    {{employee.employee_address.area}}
                                    {{employee.employee_address.city}}</br>
                                    {{employee.employee_address.state}}</br>
                                    {{employee.employee_address.country}}-
                                    {{employee.employee_address.zipcode}}
                                </address>
                            </div>
                            <div class="panel-body">
                                Phone Number : {{employee.employee_contact.phone}}
                            </div>
                            <div class="panel-body">
                                Alternate Phone Number : {{employee.employee_contact.alternate_phone}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse3"><h3>Company Details</h3></a>
                            </h4>
                        </div>
                        <div id="collapse3" class="panel-collapse collapse">
                            <div class="panel-body">Office Address </div>
                            <div class="panel-body">Zone : {{employee.primary_designation.zone.name}}</div>
                            <div class="panel-body">Location : {{employee.primary_designation.location.name}}</div>
                            <div class="panel-body">Office : {{employee.primary_designation.office.name}}</div>
                            <div class="panel-body">Department : {{employee.primary_designation.department.name}}</div>
                            <div class="panel-body">Division : {{employee.primary_designation.division.name}}</div>
                            
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse4"><h3>Designation & Reporting Officer</h3></a>
                            </h4>
                        </div>
                        <div id="collapse4" class="panel-collapse collapse">
                            
                            <div class="panel-body">Primary Designation : {{employee.primary_designation.name}}</div>
                            <div class="panel-body">Secondary Designation :
                                {% for desig in employee.secondary_designation.all %}
                                    {{desig.name}}&nbsp;
                                {% endfor %}
                            </div>
                            <div class="panel-body">Grade : {{employee.primary_designation.grade.name}}</div>
                            <div class="panel-body">Reporting Officer : {{employee.reporting_officer.user.first_name}} &nbsp;{{employee.reporting_officer.user.last_name}}-
                            {{employee.reporting_officer.primary_designation.name}}</div>
                            
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
        
    </div>
</div>
{% endblock content %}