asset/purchase_order/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [
    url(r'^$', views.index, name="list"),
    url(r'^create/$', views.create, name="create"),
    url(r'^code/settings/$', views.code_settings, name='code_settings'),
    url(r'^mail/settings/$', views.mail_settings, name='mail_settings'),
    url(r'^(?P<pk>[^/]+)/', include([
        url(r'^edit/$', views.edit, name="edit"),
        url(r'^detail/$', views.detail, name='detail'),
        url(r"^detail.pdf/$", views.InventoryPurchaseorderPDFView.as_view(), name="download-pdf"),
        url(r'^mail/$', views.purchase_order_mail, name='mail'),
        url(r'^delete/$', views.delete, name="delete"),

    ]))
]

asset/stock/urls.py
from django.conf.urls import include, url
from . import stock, item


stock_patterns = ([
    url(r'^create/$', stock.create, name='create'),
    url(r'^code/settings/$', stock.code_settings, name='code_settings'),
    url(r'^(?P<stock_pk>[^/]+)/', include([
        url(r'^detail/$', stock.detail, name='stock_detail'),
        url(r'^edit/$', stock.edit, name='stock_edit'),
        url(r'^changeStatus/$', stock.edit_status, name='editStockStatus'),
        url(r'^items/', include([
            # url(r'^add/$', item.create, name='create'),
            url(r'^(?P<item_pk>[^/]+)/delete/$', item.delete, name='delete_item'),
            url(r'^(?P<item_pk>[^/]+)/changeStatus/$', item.edit_status, name='edit-status'),
            url(r'^(?P<item_pk>[^/]+)/edit/$', item.edit, name='edit'),
            url(r'^(?P<item_pk>[^/]+)/item_detail/$', item.item_detail, name='item_detail'),
            url(r'^', item.items, name='list'),
        ], namespace="item")),
    ])),

    # url(r'^batches/', include([
    #     url(r'^(?P<batch_pk>[^/]+)/', include([
    #         url(r'^changeStatus/$', batch.edit_status, name='edit-status'),
    #         url(r'^delete/$', batch.delete, name='delete'),
    #         url(r'^edit/$', batch.edit, name='edit'),

    #         url(r'^items/', include([
    #             url(r'^add/$', item.create, name='create'),
    #             url(r'^delete/$', item.delete, name='delete_item'),
    #             url(r'^(?P<item_pk>[^/]+)/changeStatus/$', item.edit_status, name='edit-status'),
    #             url(r'^(?P<item_pk>[^/]+)/edit/$', item.edit, name='edit'),
    #             url(r'^(?P<item_pk>[^/]+)/item_detail/$', item.item_detail, name='item_detail'),
    #             url(r'^', item.items, name='list'),
    #         ], namespace="item")),
    #     ])),
    # ], namespace="batch")),

    # url(r'^stock/batch/(?P<batch_pk>[^/]+)/edit/$', stock.edit_batch, name='edit_batch'),
    # url(r'^stock/batch/item/(?P<item_pk>[^/]+)/edit/$', stock.edit_item, name='edit_item'),

    url(r'^products/checkStock/$', stock.checkStock, name='checkStock'),
    url(r'^asset/lists/$', item.assetLists, name='assetLists'),
    url(r'^asset/staffAssetlists/$', item.staff_asset_lists, name='staff_asset_lists'),


    # # For mobile view The below links
    # # search for stock via product code- Get
    # url(r'^batch/product/(?P<code>[\w\-]+)/$', batch.batch_detail),
    # url(r'^batch/(?P<batch_pk>[^/]+)/statusBooked/$', batch.batch_status_booked),
    # url(r'^batch/(?P<batch_pk>[^/]+)/cancelBooked/$', batch.batch_cancel_booked),
    url(r'^', stock.index, name="list"),
])

asset/urls.py
from django.conf.urls import include, url
from asset import asset, asset_type
from .stock.urls import stock_patterns

app_name = "asset"

asset_type_patterns = ([
    url(r'^asset_type/', include([

        url(r'^create/$', asset_type.create, name="create"),
        url(r'^asset_category/$', asset_type.asset_category, name="asset_category"),

    ])),

], 'asset_type')


urlpatterns = [

    url(r'^asset/', include([
        url(r'^index/$', asset.index, name="list"),
        url(r'^dashboard/$', asset.dashboard, name="dashboard"),
        url(r'^create/$', asset.create, name="create"),
        url(r'^customer/asset/create/$', asset.customer_asset_create, name="customer_asset_create"),
        url(r'^customer/asset/(?P<pk>[^/]+)/edit/$', asset.customer_asset_edit, name="customer_asset_edit"),
        url(r'^(?P<pk>[^/]+)/edit/$', asset.edit, name="edit"),
        url(r'^(?P<pk>[^/]+)/detail/$', asset.detail, name="detail"),
        url(r'^(?P<pk>[^/]+)/delete/$', asset.delete, name="delete"),
        url(r'^stocks/', include(stock_patterns, namespace="stock")),
        url(r'^code/settings/$', asset.code_settings, name='code_settings'),
        url(r'^(?P<barcode>[^/]+)/transaction/$', asset.asset_transaction, name="asset_transaction"),

    ])),
    url(r'^asset/', include(asset_type_patterns)),
    url(r'^transaction/(?P<pk>[^/]+)/detail/$', asset.transaction_detail, name="transaction_detail"),
    url(r'^customer/transactions/(?P<selectedDate>[^/]+)/$', asset.customer_transaction, name="customer_transaction"),
    url(r'^customer/transactions/$', asset.customer_transaction, name="customer_transaction"),
    url(r'^customer/assets/(?P<date>[^/]+)/(?P<customer>[^/]+)/$', asset.customer_asset, name="customer_asset"),
    url(r'^asset/change/status/(?P<pk>[^/]+)/$', asset.changeStatus, name="changeStatus"),
    url(r'^employee/assets/$', asset.employee_assets, name="employee_assets"),
    url(r'^return/asset/(?P<pk>[^/]+)/$', asset.return_asset, name="return_asset"),


]

papercraneerp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from sitetree.sitetreeapp import compose_dynamic_tree, register_dynamic_trees
from erp_admin import views as erpAdminViews


# from employee import views as employeeViews
urlpatterns = [
    url(r'^$', erpAdminViews.dashboard),
    # url(r'^api-token-auth/', views.obtain_auth_token),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('employee.urls', namespace="employee")),
    url(r'^', include('customer.urls', namespace="customer")),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include('location.urls', namespace="location")),
    url(r'^company/', include('company.urls', namespace="company")),
    url(r'^', include('asset.urls', namespace="asset")),




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns = static(settings.MEDIA_URL, view=never_cache(serve_static),
#                          document_root=settings.MEDIA_ROOT) + urlpatterns
admin.site.site_header = 'Jawdrop Administration'




register_dynamic_trees(

    compose_dynamic_tree('erp_admin'),

    # or gather all the trees from `books` and attach them to `main` tree root,
    compose_dynamic_tree('employee'),
    compose_dynamic_tree('customer'),
    compose_dynamic_tree('asset'),





)

asset/purchase_order/views.py
from django.db.models import F
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib import messages
from django.core.mail import BadHeaderError, EmailMultiAlternatives
from django.forms import inlineformset_factory
from django.template.loader import get_template
from django.template import Context
from django.utils import timezone
from erp_core.pagination import paginate
from easy_pdf.views import PDFTemplateView
from easy_pdf.rendering import render_to_pdf
from asset.stock.models import Stock
from .models import Asset as Product
from location.models import Location
from .forms import PurchaseOrderForm, ItemForm, PurchaseOrderEditForm, CodeSettingForm, MailSettingsForm
from .models import PurchaseOrder, MailSetting, PurchaseOrderItem as Item, PurchaseOrderCodeSetting as CodeSetting
from .filters import PurchaseOrderFilter
from django.db import IntegrityError, transaction


def index(request):
    # print(request.GET)

    f = PurchaseOrderFilter(request.GET, queryset=PurchaseOrder.objects.all().order_by("-created_at"))
    # purchaseorders = InventoryPurchaseOrder.objects.all()

    purchaseorders, pagination = paginate(request, queryset=f.qs, per_page=15, default=True)
    context = {

        'purchaseorders': purchaseorders,
        'pagination': pagination,
        'filter': f,
    }

    return render(request, "asset/purchase_order/list.html", context)


@transaction.atomic
def create(request):

    PurchaseItemInlineFormSet = inlineformset_factory(
        PurchaseOrder, Item, form=ItemForm, extra=0, can_delete=True, min_num=1, validate_min=True)
    purchase_item_formset = PurchaseItemInlineFormSet(request.POST or None)
    locations = Location.objects.all()
    purchase_order_form = PurchaseOrderForm(request.POST or None)
    if request.method == "POST":
        if purchase_order_form.is_valid() and purchase_item_formset.is_valid():
            try:
                with transaction.atomic():

                    purchase_order = purchase_order_form.save(commit=False)
                    purchase_order.issued_by = request.user.employee
                    purchase_order.issued_date = timezone.now()
                    purchase_order.save()

                    items = purchase_item_formset.save(commit=False)
                    for item in items:
                        item.purchase_order = purchase_order
                        # item.setAfterDiscount()
                        item.save()
                        # set sales order foreign key
                        purchase_order.setAmount().save()

                    # stock create
                    cur_location = request.POST['location']
                    location = Location.objects.get(id=cur_location)
                    Stock.objects.create(
                        code=Stock.newCode(), date_time=timezone.now(), location=location, purchase_order=purchase_order
                    )
                    return redirect(reverse('asset:purchase_order:detail', args=[purchase_order.id]))
            except IntegrityError:
                messages.add_message(request, messages.SUCCESS,'Please make sure that stock code setting is done or not')
                return redirect(reverse('asset:purchase_order:create'))

    context = {
        'purchaseorder_form': purchase_order_form,
        'purchase_item_formset': purchase_item_formset,
        'form_url': reverse_lazy('asset:purchase_order:create'),
        'type': "Create",
        'locations': locations,
        'products': Product.fixed_asset.all(),

    }

    return render(request, "asset/purchase_order/edit.html", context)


@transaction.atomic
def edit(request, pk=None):
    purchase_order = get_object_or_404(PurchaseOrder, id=pk)

    purchase_order_form = PurchaseOrderEditForm(request.POST or None, instance=purchase_order)

    PurchaseItemInlineFormSet = inlineformset_factory(
        PurchaseOrder, Item, form=ItemForm, extra=0, can_delete=True, min_num=1, validate_min=True)
    purchase_item_formset = PurchaseItemInlineFormSet(request.POST or None, instance=purchase_order)

    if request.method == "POST":

        if purchase_order_form.is_valid() and purchase_item_formset.is_valid():
            purchase_order_item = purchase_order_form.save(commit=False)
            purchase_order_item.save()
            purchase_item_formset.save()
            purchase_order_item.setAmount().save()

            return redirect(reverse('asset:purchase_order:detail', args=[purchase_order.id]))

    context = {
        'purchaseorder_form': purchase_order_form,
        'purchase_item_formset': purchase_item_formset,
        'form_url': reverse_lazy('asset:purchase_order:edit', args=[purchase_order.pk]),
        'type': "Edit",
        'purchase_order': purchase_order,
        'products': Product.fixed_asset.all(),
    }
    return render(request, "asset/purchase_order/edit.html", context)


def detail(request, pk):
    purchase_order = get_object_or_404(PurchaseOrder, id=pk)
    items = purchase_order.order_items
    context = {
        'purchaseorder': purchase_order,
        'items': items,

    }
    return render(request, "asset/purchase_order/detail.html", context)


@transaction.atomic
def code_settings(request):
    if CodeSetting.objects.exists():
        code_form = CodeSettingForm(request.POST or None, instance=CodeSetting.objects.last())
    else:
        code_form = CodeSettingForm(request.POST or None)

    if request.method == "POST":
        if code_form.is_valid():
            code_form.save()
            return redirect(reverse('asset:purchase_order:list'))

    context = {
        'code_form': code_form,
    }

    return render(request, "asset/purchase_order/code_setting.html", context)


def mail_settings(request):

    if MailSetting.objects.exists():
        mail_form = MailSettingsForm(request.POST or None, instance=MailSetting.objects.last())
    else:
        mail_form = MailSettingsForm(request.POST or None)

    if request.method == "POST":

        if mail_form.is_valid():
            mail_form.save()
            return HttpResponseRedirect(reverse('asset:purchase_order:list'))

    context = {

        'mail_form': mail_form,
    }

    return render(request, "asset/purchase_order/mail_settings.html", context)


class InventoryPurchaseorderPDFView(PDFTemplateView):

    template_name = "asset/purchase_order/purchaseorder_pdf.html"

    def get_context_data(self, **kwargs):
        pk = kwargs.get('pk', False)
        purchase_order = get_object_or_404(PurchaseOrder, id=pk)
        items_pro = purchase_order.order_items
        return super(InventoryPurchaseorderPDFView, self).get_context_data(
            pagesize="A4",
            title="Purchase Order",
            purchaseorder=PurchaseOrder.objects.get(pk=pk),
            items=items_pro,
            # products=PurchaseOrderItems.objects.all(),
        )


def purchase_order_mail(request, pk):
    mail_list = []
    purchase_order = PurchaseOrder.objects.get(pk=pk)
    products = purchase_order.order_items
    mail_settings = MailSetting.objects.last()
    if request.method == "POST":
        source = request.POST.get('source', False)

        destination = request.POST.get('destination', False)
        subject = request.POST.get('subject', False)
        content = request.POST.get('message', False)
        cc = request.POST.get('cc', False)

        if source and destination and subject and content:

            if MailSetting.objects.exists():
                group_cc = MailSetting.objects.last().group_cc.all()
                for gcc in group_cc:
                    mail_list.append(gcc.user.email)

            # attachement = request.POST.get('attachement', False)

            attachement_content = {
                'purchaseorder': purchase_order,
                'products': products
            }
            pdf_attachment = render_to_pdf("asset/purchase_order/raw_material_purchase_order_pdf.html",
                                           attachement_content, encoding='utf-8')
            # send_mail(source,destination,subject,content,attachement)
            htmly = get_template('asset/purchase_order/email.html')

            d = Context({'purchaseorder': purchase_order, 'content': content})

            html_content = htmly.render(d)
            try:
                if not MailSetting.objects.exists():
                    msg = EmailMultiAlternatives(subject, "Purchaseorder", source, [destination, cc])
                else:
                    msg = EmailMultiAlternatives(
                        subject, "Purchaseorder", source, [destination], cc=[cc], bcc=['mail_list']
                    )
                msg.attach_alternative(html_content, "text/html")
                msg.attach("purchase-order.pdf", pdf_attachment, 'application/pdf')
                msg.send()

            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            messages.add_message(request, messages.ERROR, "Purchase order send successfully")
            purchase_order.send_mail = True
            purchase_order.save()

            return redirect(reverse('asset:purchase_order:detail', args=[purchase_order.id]))

    context = {

        'purchaseorder': purchase_order,
        'mail_settings': mail_settings,
    }
    return render(request, "asset/purchase_order/mail.html", context)
# Generating pdf


def delete(request, pk):
    if request.method == "POST":
        purchaseorder = get_object_or_404(PurchaseOrder, id=pk)
        # print("delete")
        purchaseorder.delete()
    return HttpResponseRedirect(reverse('asset:purchase_order:list'))

asset/views.py
from django.shortcuts import render

# Create your views here.

asset/templates/transaction/assets.html
{% extends "erp_admin/base.html" %}
{% load static tz group_required %}
{% get_current_timezone as TIME_ZONE %}
{% block head %}


<style>

</style>
{% endblock head %} {% block content %}
<div class="banner">

      <h3>Assets</h3>


</div>
<div>

    <div class="block">
        <div class="row show-grid">
            <form method="get">

                <div class="col-sm-4 col-xs-12">


                    <select class="form-control" name="employee">
                        <option value="">Select Employee</option>

                            {% for employee in employees %}

                            <option value="{{employee.pk}}">{{employee}}</option>
                            {% endfor %}

                    </select>

                 </div>
                <div class="col-sm-4 col-xs-12">

                    <input type="text" class="form-control tdate" name="date" placeholder="Select Date">

                 </div>
                 <div class="col-sm-4 col-xs-12">
                     <button type="submit" class="btn btn-primary"> <i class="fa fa-search"></i> Search</button>
                     <a href="{% url 'asset:employee_assets' %}" class="btn btn-primary"><i class="fa fa-refresh"></i> Refresh</a>

                 </div>
            </form>


            <div class="col-sm-12 col-xs-12 table-responsive">
                <div>
                    <span> {% if assets %} Date : {{selected_date}} {% if not employee == "" %} &&   Employee: {{employee}}{%endif %}{% endif %}</span>
                </div>
                            <table class="table stripped" style="margin-top:3%;">

                                <thead></thead>
                                <tbody>

                                    {% for asset in assets %}


                                    <tr class="table-row">

                                        <td class="table-text">
                                            <h6>
                                                {{asset.asset}}
                                            </h6>
                                            <p></p>
                                        </td>



                                         <td >
                                           <button class="btn btn-primary btn-sm statusbutton" data-value="{{asset.asset.pk}}">

                                                    Return&nbsp;&nbsp;&nbsp;&nbsp; <i class="fa fa-arrow-left"></i>


                                           </button>
                                        </td>
                                    </tr>

                                    {% empty %}
                        <tr>
                            <td colspan="4">No Assets</td>
                        </tr>
                        {% endfor %}


                        </tbody>
                    </table>
            </div>


        </div>
    </div>
</div>


<!--Modal -->


{% endblock content %}

{% block jsscript %}


<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/daterangepicker.js' %}"></script>

<script>

function getCookie(name) {
   var cookieValue = null;
   if (document.cookie && document.cookie != '') {
       var cookies = document.cookie.split(';');
       for (var i = 0; i < cookies.length; i++) {
           var cookie = jQuery.trim(cookies[i]);
           // Does this cookie string begin with the name we want?
           if (cookie.substring(0, name.length + 1) == (name + '=')) {
               cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
               break;
           }
       }
   }
   return cookieValue;
}
var csrftoken = getCookie('csrftoken');
function csrfSafeMethod(method) {
   // these HTTP methods do not require CSRF protection
   return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
   beforeSend: function(xhr, settings) {
       if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
           xhr.setRequestHeader("X-CSRFToken", csrftoken);
       }
   }
});

$(document).ready(function() {

 $('.tdate').daterangepicker({
        singleDatePicker: true,
        // calender_style: "picker_4",
        showDropdowns: true,
        locale: {
            format: 'YYYY-MM-DD',
                },
    }, function(start, end, label) {
        console.log(start.toISOString(), end.toISOString(), label);
    });


     $(".statusbutton").click(function(event){

       <!--var selectedStatus = $(this).children("option:selected").val();-->
       var primek = $(this).data("value")
       console.log(primek)
       if (confirm("Confirm?"))
       var $buton = $(this);

       {
           $.ajax(
           {
               url : '/return/asset/' + primek + '/',
               type: "POST",
               data: {
                 <!--'status': selectedStatus-->
               },
               success:function(data)
               {
                   console.log('success')
                   alert("Asset has been return successfully")
                   $buton.parent().parent().remove();



               },
               error: function(jqXHR, textStatus, errorThrown)
               {
                   console.log('failed')
               }
           });
       }
   });

   });


</script>

{% endblock jsscript %}

asset/templates/transaction/detail.html
{% extends "erp_admin/base.html" %}
{% load static tz %}
{% get_current_timezone as TIME_ZONE %}
{% block head %}
<style>
.row{
    margin-left:5px;
    margin-right:5px;
}
</style>
{% endblock head %}
{% block content %}

<div id="quotation-block" v-cloak>
    <div class="block">
        <a href="{% url 'asset:list' %}">Back </a>
        <div class="row show-grid">
            <div class="row">
                <div class="col-sm-8 col-xs-12">
                    <h3>{{transaction.customer}}</h3>
                </div>

            </div>
        </div>
    </div>

    <div class="block">

        <div class="row show-grid">
            <div class="row">
                <div class="col-sm-6 col-xs-12" style="">
                    <span class="date_font">
                        Created date: {{ transaction.created_at }}
                    </span>
                </div>
                <div class="col-sm-6 col-xs-12">
                    <span class="date_font pull-right">
                        Last Update: {{ transaction.updated_at | date }}
                    </span>
                </div>
            </div>
        </div>
        <div class="row show-grid">
            <div class="col-sm-8">
                <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>


                    </thead>
                    <tbody>
                         <tr>
                            <th>Asset</th>
                            <td>{{ transaction.asset }}</td>
                        </tr>
                         <tr>
                            <th>Picked Date and time</th>
                            <td>{{ transaction.date_and_time}}</td>
                        </tr>



                        <tr>
                            <th>Handover From</th>
                            <td>{{ transaction.source }}</td>
                        </tr>
                         <tr>
                            <th>Handover To</th>
                            <td>{{transaction.destination }}</td>
                        </tr>

                        <tr>
                            <th>Created By</th>
                            <td>{{ transaction.created_by }}</td>
                        </tr>

                     <tr>
                            <th>Updated By</th>
                            <td>{{ transaction.updated_by }}</td>
                     </tr>

                    {%  if transaction.asset_status %}

                         <tr>
                                <th>Asset Status</th>
                                <td>{{ transaction.asset_status }}</td>
                         </tr>
                    {% endif %}

                      <tr>
                            <th>Usage Status</th>
                          <td>{{ transaction.usage_status }}</td>
                     </tr>


                    </tbody>
                </table>
                </div>
            </div>
        </div>




    </div>
</div>





{% endblock content %}

{% block jsscript %}

{% endblock jsscript %}

asset/templates/transaction/employee_assets.html
{% extends "erp_admin/base.html" %}{% load humanize %}
{% load static %}
{% block head %}
<style>
    .tab{
    border-radius:11px!important;
    width: 48%;
    }
</style>

{% endblock head %}
{% block content %}

<div class="modal fade" id="filter-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Filters</h4>
      </div>
      <div class="modal-body">
        <form action="" method="get">
            {# {{ filter.form }} #}

            <div class="col-sm-6">
                <div class="form-group">
                    <label class="control-label">{{ filter.form.name.label }}</label>
                    {{ filter.form.name }}
                </div>
            </div>
             <div class="col-sm-6">
                <div class="form-group">
                    <label class="control-label">{{ filter.form.asset_type.label }}</label>
                    {{ filter.form.asset_type }}
                </div>
            </div>




            <div class="clearfix"></div>
            <h4 style="padding: 10px;">Sort By</h4>
            <div class="col-sm-12">
                <div class="form-group">
                    <label class="control-label">{{ filter.form.order_by_created_at.label }}</label>
                    {{ filter.form.order_by_created_at }}
                </div>
            </div>


            <button type="submit" class="btn btn-primary pull-right">Submit</button>
            <div class="clearfix"></div>
        </form>
      </div>
      <div class="modal-footer">

      </div>
    </div>
  </div>
</div>

	<div class="content-main">
		<div class="block">
			<div class="row show-grid">
				<div class="col-sm-6">

					<h3>Assets</h3>
				</div>
                <div>
                    <a href="{% url 'asset:customer_transaction' %}"><i class="fa fa-close pull-right"></i></a>
                </div>

			</div>
			<div class="row show-grid">
				<div class="col-sm-12">
                    <div class="table-responsive">

						<table class="table table-striped">
							<thead>
								<tr>
                                    <th>#</th>
                                    <th>Customer</th>
                                    <th>Asset</th>
                                    <th>Time</th>
                                    <th>Status</th>


                                </tr>
							</thead>
							<tbody>
								{% for asset in assets %}
									<tr>
										<td scope="row">{{ forloop.counter }}</td>
                                         <td>{{asset.customer}}</td>
                                        <td>{{asset.asset}}</td>
                                        <td>{{asset.date_and_time}}</td>
                                        <td>

                                            <select class="form-control statusbutton tab" name="status" data-value="{{ asset.pk }}">

                                                <option{% if asset.usage_status == "Not Used" %}selected{% endif %}><a href="" data-value="Not Used">Not Used</a></option>
                                                <option {% if asset.usage_status == "Used" %}selected{% endif %}><a href="" data-value="Used">Used</a></option>
                                                <option {% if asset.asset_status == "Damage" %}selected{% endif %}><a href="" data-value="Damage">Damage</a></option>
                                                 <option {% if asset.asset_status == "Destroyed" %}selected{% endif %}><a href="" data-value="Destroyed">Destroyed</a></option>

                                            </select>
                                        </td>


                                    </tr>
									{% empty %}
									<tr><td>No Assets</td></tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
					<div id="pagination">
						{{pagination|safe}}
					</div>

				</div>
			</div>
		</div>
	</div>
{% endblock content %}

{% block jsscript %}
<script>

function getCookie(name) {
   var cookieValue = null;
   if (document.cookie && document.cookie != '') {
       var cookies = document.cookie.split(';');
       for (var i = 0; i < cookies.length; i++) {
           var cookie = jQuery.trim(cookies[i]);
           // Does this cookie string begin with the name we want?
           if (cookie.substring(0, name.length + 1) == (name + '=')) {
               cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
               break;
           }
       }
   }
   return cookieValue;
}
var csrftoken = getCookie('csrftoken');
function csrfSafeMethod(method) {
   // these HTTP methods do not require CSRF protection
   return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
   beforeSend: function(xhr, settings) {
       if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
           xhr.setRequestHeader("X-CSRFToken", csrftoken);
       }
   }
});
$(document).ready(function() {
    $(".statusbutton").change(function(event){
        alert("yu")
       var selectedStatus = $(this).children("option:selected").val();
       var primek = $(this).data("value")
       if (confirm("Confirm?"))
       $(this).val(selectedStatus);
       {
           $.ajax(
           {
               url : '/asset/change/status/' + primek + '/',
               type: "POST",
               data: {
                 'status': selectedStatus
               },
               success:function(data)
               {
                   console.log('success')
               },
               error: function(jqXHR, textStatus, errorThrown)
               {
                   console.log('failed')
               }
           });
       }
   });
   });

</script>

{% endblock jsscript %}